name: Update

on:
  # Runs at 10:00 UTC every day
  schedule:
    - cron:  '0 10 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: 🔄 Sync version with upstream
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Sync version with upstream
        uses: snapcrafters/ci/sync-version@main
        shell: bash
        with:
          token: ${{ secrets.SNAPCRAFTERS_BOT_COMMIT }}
          update-script: |
            latest_stable_tesseract_version="$(
              git ls-remote --sort=-v:refname --tags --refs https://github.com/tesseract-ocr/tesseract.git \
                | cut -d '/' -f 3 \
                | grep -Eve '(alpha|b|beta|dev|rc)' \
                | head -n1
            )"
            sed -Ei -e "s/^(version: ).*$/\\1${latest_stable_tesseract_version}/" snap/snapcraft.yaml

            latest_stable_leptonica_version="$(
              git ls-remote --tags --refs https://github.com/DanBloomberg/leptonica.git \
                | cut -d '/' -f 3 \
                | grep -Eve '(alpha|beta|dev|rc)' \
                | sed -Ee '/^v/d' \
                | sort -rV \
                | head -n1
            )"
            yq -ie ".parts.leptonica.source-tag = \"${latest_stable_leptonica_version}\"" snap/snapcraft.yaml
